packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@michengai/dsh-btw@0.1.15'
  - '@michengai/dsh-code-review@0.1.9'
  - '@michengai/dsh-codex-ui@1.1.25'
  - '@michengai/dsh-simplify@0.1.12'
  - dsh-cost-meter@1.7.47
  - dsh-whale-girl-pet@0.3.7
  - '@mrweicodes/dsh-loop-guard@1.0.8'
  - '@goodandready/dsh-key-limits@0.2.19'
  - 'dsh-inline-figures@0.1.0'
  - 'dsh-prompt@0.3.0'
  - 'dsh-workbuddy-connect@0.7.1'
